meenfee_dev/accounts/api/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import *

urlpatterns = [
    path('register/',UserCreateAPIView.as_view(),name="register"),
	path('login/',UserLoginAPIView.as_view(),name="login"),
	path('changepassword/',ChangePasswordAPIView.as_view(),name="changePassword"),
    path('otp-generate',ResetPasswordOtpGenerateAPIView.as_view(),name="OtpGenerateAPIView"),
    path('otp-verify',ResetPasswordOtpVarifyAPIView.as_view(),name="OtpVarifyAPIView"),
    path('change/usertype',SwitchUserTypeAPIView.as_view(),name="SwitchUserType"),
    path('password/reset/otp',ForgetPasswordOtpAPIView.as_view(),name='ChangePassword'),
    path('phone-no/otp-generate',MobileNumberGenerateOtp.as_view(),name='MobileNumberOtpGeneration'),  #To Be Enabled in Production
    path('phone-no/otp-verify',MobileNumberVerifyOtp.as_view(),name='MobileNumberVerification'),
    path('resetPassword/sms/otp-generate',ResetPasswordBySMS.as_view(),name="Reset Password OTP Generate"),
    path('resetPassword/sms/otp-verify',ResetPasswordBySMSVerify.as_view(),name="Reset Password Verify"),
    path('setPassword',SetNewPassword.as_view(),name="Set Password"),
    path('resetPassword/email/otp-generate',ResetPasswordByEmail.as_view(),name="Reset Password By Email OTP Generate"),
    path('resetPassword/email/otp-verify',ResetPasswordByEmailVerify.as_view(),name="Reset Password By Email OTP Verify"),
    path('resend/otp',ResendOTP.as_view(),name="Resend OTP"),
    path('update_missing_info/',SocialLoginMissingInfo.as_view(),name="Social Login Missing Info"),
    path('social_login/facebook/',FacebookLogin.as_view(),name="Facebook Login"),
    path('social_login/google/',GoogleLogin.as_view(),name="Google Login"),
    path('logout/',Logout.as_view(),name="Logout"),
    path('update/idcard',UpdateIDCard.as_view(),name="UpdateIDCard")
]

meenfee_dev/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import activate
from django.views.generic.base import TemplateView
from rest_framework_jwt.views import (
    refresh_jwt_token,
    obtain_jwt_token,
    verify_jwt_token
    )

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^api/v1/users/',include(('accounts.api.urls','accounts'),namespace="users-api")),
    url(r'^api/',include(('meenfee.api.urls','meenfee'),namespace="meenfee")),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),#Email Activation
    url('^', include('django.contrib.auth.urls')), #email varification
    # url(r'^rest-auth/', include('rest_auth.urls')), #social login
    url(r'^accounts/',include('allauth.urls'), name='socialaccount_signup'),
    path('adminpanel/', include('adminpanel.urls')),
    path('adminpanel/services/', include('services.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meenfee_dev/services/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.service_main, name='service_main'),
    path('add-service', views.add_service, name='add_service'),
    path('add-category', views.add_category, name='add_category'),
    path('add-subcategory', views.add_subcategory, name='add_subcategory'),    
    path('category-list', views.catgory_list, name='catgory_list'),
    path('subcate-list', views.subcategory_list, name='subcategory_list'),    
    path('catedelete/<int:id>/', views.delete_category, name='delete_category'),
    path('scatedelete/<int:id>/', views.delete_subcategory, name='delete_subcategory'),    
    path('get_table_values', views.get_table_values, name='get_table_values'),
    path('services-list', views.services_list, name='services_list'),    
    path('servicedelete/<int:id>/', views.delete_service, name='delete_service'), 
    path('add-content', views.add_content, name='add_content'), 
    path('content-list', views.content_list, name='content_list'),
    path('contentdelete/<int:id>/', views.delete_content, name='delete_content'),     
    path('banner-list', views.banner_list, name='banner_list'),    
    path('bannerdelete/<int:id>/', views.delete_banner, name='delete_banner'), 
    path('add-banner', views.add_banner, name='add_banner'),  
    path('userrating-list', views.userrating_list, name='userrating_list'),
    path('add-rating', views.add_rating, name='add_rating'),
    path('edit-service/<int:id>/', views.edit_service, name='edit_service'),
    
    path('edit-images/<int:id>/', views.edit_image, name='edit_image'),    
    path('payment', views.payment_process, name='payment_process'),
    
    path('add-rating', views.add_rating, name='add_rating'),
    path('deleterating', views.delete_rating, name='delete_rating'),
    path('list-rating', views.list_rating, name='list_rating'),
   
    path('list-pservices/<int:id>/', views.list_pservices, name='list_pservices'),
    path('list-pservices-reviews/<int:id>/', views.list_pservices_reviews, name='list_pservices_reviews'),
    path('mod-review/<int:id>/', views.mod_review, name='mod_review'),
    
    
    path('payment-list', views.payment_list, name='payment_list '),
    path('pay-refund-list', views.pay_refund_list, name='pay_refund_list'),
    path('pay-complete-list', views.pay_complete_list, name='pay_complete_list'),   
    
    path('list-questions', views.list_questions, name='list_questions '), 
    path('list-answers/<int:id>/', views.list_answers, name='list_answers'),
    
    path('deletequestion/<int:id>/', views.delete_question, name='delete_question'),
    path('deleteanswer/<int:id>/', views.delete_answer, name='delete_answer'),
    
    path('edit-category/<int:id>/', views.edit_category, name='edit_category'),
    
    path('related-subcategory/<int:id>/', views.related_subcategory, name='related_subcategory'),
    path('edit-subcategory/<int:id>/', views.edit_subcategory, name='edit_subcategory'),
    path('edit-banner/<int:id>/', views.edit_banner, name='edit_banner'),
    
    path('add-questions/<int:id>/', views.add_questions, name='add_questions'),
    path('type-questions/', views.type_questions, name='type_questions'),
    path('get_services_values', views.get_services_values, name='get_services_values'), 
    
    path('service_based_questions/<int:id>/', views.service_based_questions, name='service_based_questions'),

    path('deactivate-payment/<int:id>/',views.deactivate_payments,name='deactivate_payments')
           
]
#ClixAdm?!6611

meenfee_dev/services/models.py
from django.db import models
from django.utils.text import slugify
from tinymce import HTMLField


COLOR_CHOICES = (
    ('green','GREEN'),
    ('blue', 'BLUE'),
    ('red','RED'),
    ('orange','ORANGE'),
    ('black','BLACK'),
)
 

class ContentMaster(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=250,null=True)
    content = HTMLField('Content')
    
    title_in_arabic = models.CharField(max_length=120)
    description_in_arabic = models.TextField(max_length=250,null=True)
    content_in_arabic = HTMLField('Content in Arabic')
    
    legal_text = models.TextField(blank=True,null=True)
    
    # main_content = models.TextField(blank=True,null=True)
    # main_content_arabic = models.TextField(blank=True,null=True)

    # main_content = HTMLField('Content')
    # main_content_arabic = HTMLField('Content in Arabic')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'meenfee_content_master'




class CategoryMaster(models.Model):
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=100)
    description= models.CharField(max_length=500)

   # color = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')
    #uom_id = models.IntegerField(default=1)
   # uom_id = models.CharField(default="--Select--",max_length=255)
    #company_id = models.IntegerField(default=1)
    
    user_id = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)
    inactive_date= models.CharField(max_length=500)
    created_by= models.IntegerField(default=1)
    created_date = models.CharField(max_length=500)
    updated_by= models.IntegerField(default=1)
    updated_date= models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.code


    class Meta:
        db_table = 'meenfee_category_master'
        
        
        
class SubCategoryMaster(models.Model):
    category_id= models.IntegerField(default=1)
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=100)
    description= models.CharField(max_length=500)

   # color = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')
    #uom_id = models.IntegerField(default=1)
   # uom_id = models.CharField(default="--Select--",max_length=255)
    #company_id = models.IntegerField(default=1)
    
    user_id = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)
    inactive_date= models.CharField(max_length=500)
    created_by= models.IntegerField(default=1)
    created_date = models.CharField(max_length=500)
    updated_by= models.IntegerField(default=1)
    updated_date= models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.code


    class Meta:
        db_table = 'meenfee_sub_category_master'

meenfee_dev/services/forms.py
from django import forms
from django.forms import ValidationError
from django.core.exceptions import ValidationError

from tinymce import TinyMCE
from .models import ContentMaster

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)


class BannerImageUploadForm(forms.Form):
    """Banner Image upload form."""
    banner_image = forms.ImageField(required=False)


class CategoryImageUploadForm(forms.Form):
    """Category Image upload form."""
    bannerimage = forms.ImageField()
    
    
class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False



class ContentFormNew(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control ', }
    ), required=True,max_length=40)

    title_in_arabic = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control ', }
    ), required=False,max_length=40)

    # main_content = forms.CharField(widget=TinyMCEWidget(
    #         attrs={'required': True, 'cols': 30, 'rows': 10}
    #     ), required=True)

    # main_content_arabic = forms.CharField(widget=TinyMCEWidget(
    #         attrs={'required': True, 'cols': 30, 'rows': 10}
    #     ), required=True)

    content = forms.CharField(widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        ), required=True,max_length=30000)

    content_in_arabic = forms.CharField(widget=TinyMCEWidget(
            attrs={'required': True, 'cols': 30, 'rows': 10}
        ), required=True,max_length=30000)

    class Meta:
        model = ContentMaster
        fields = [
            'title',
            'title_in_arabic',
            # 'main_content',
            # 'main_content_arabic',
            'content',
            'content_in_arabic'
            ]





# class ContentForm(forms.ModelForm):
#     content = forms.CharField(
#         widget=TinyMCEWidget(
#             attrs={'required': False, 'cols': 30, 'rows': 10}
#         ), 
#     )
#     description = forms.CharField(widget=forms.Textarea(
#         attrs={'rows': 3,'cols':5,'class': 'form-control ', }
#     ),required=True, max_length=100)
    
#     title = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control ', }
#     ), required=True,max_length=40)
    
    
    
#     content_in_arabic = forms.CharField(
#         widget=TinyMCEWidget(
#             attrs={'required': False, 'cols': 30, 'rows': 10}
#         ), required=False,
#     )
#     description_in_arabic = forms.CharField(widget=forms.Textarea(
#         attrs={'rows': 3,'cols':5,'class': 'form-control ', }
#     ), required=False, max_length=100)
    
#     title_in_arabic = forms.CharField(widget=forms.TextInput(
#         attrs={'class': 'form-control ', }
#     ), required=False,max_length=40)
    
#     class Meta:
#         model = ContentMaster
#         fields = '__all__'
        
        
   
    
    

meenfee_dev/services/templates/add_category.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type">Add Category</h2>
{% endblock %}
{% block card%}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<form class="form-horizontal add_user" action="" method="post" enctype="multipart/form-data">
  <div class="panel panel-default">
    <div class="panel-heading user-form">


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Category Name</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="name" type="text" maxlength="35" required name="name" placeholder="Category">
        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Category Name (Arabic)</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" dir="rtl" id="name" type="text" maxlength="35" required name="name_arabic" placeholder="الفئة">
        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Category Image</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="id_bannerimage" required type="file" name="bannerimage">

        </div>
      </div>



      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="user_address">Description</label>
        <div class="col-md-4 offset-md-3">
          <textarea maxlength="500" class="form-control" id="description" required name="description" rows="5"
            placeholder="Description..."></textarea>
        </div>
      </div>


      <div class="card-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="fa fa-dot-circle-o"></i> Submit</button>
        <button class="btn btn-sm btn-danger" type="reset">
          <i class="fa fa-ban"></i> Reset</button>
      </div>
    </div>
  </div>
  </div>
</form>
{% endblock %}
{% block card2%}
{% endblock %}

{% block jsbody%}
{%endblock%}

meenfee_dev/services/templates/add_content.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type">Add Content</h2>
{% endblock %}
{% block card%}
{{ form.media }}
<form class="form-horizontal add_user" action="" method="post" enctype="multipart/form-data">
  <div class="panel panel-default">
    <div class="panel-heading user-form">

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Title</label>
        <div class="col-md-4 offset-md-3">
          {{ form.title }}
        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Title (Arabic)</label>
        <div class="col-md-4 offset-md-3">
          {{ form.title_in_arabic }}
        </div>
      </div>

      <!-- <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Description</label>
        <div class="col-md-4 offset-md-3">
          {{ form.description }}
        </div>
      </div> -->

      <!-- <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Content</label>
        <div class="col-md-4 offset-md-3">
          {{ form.content }}
          <input type="hidden" name="isarabic" id="isarabic" value="true" />
        </div>
      </div> -->

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Content</label>
        <div class="col-md-4 offset-md-3">
          {{ form.content }}
          <!-- <input type="text" name="content" id="content" value="true" /> -->
        </div>
      </div>


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Content (Arabic)</label>
        <div class="col-md-4 offset-md-3">
          {{ form.content_in_arabic }}
          <input type="hidden" name="content_arabic" id="content_arabic" value="true" />
          <input type="hidden" name="isarabic" id="isarabic" value="true" />
        </div>
      </div>


      <div class="card-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="fa fa-dot-circle-o"></i> Submit</button>
        <button class="btn btn-sm btn-danger" type="reset">
          <i class="fa fa-ban"></i> Reset</button>
      </div>
    </div>
  </div>
  </div>
</form>



{% endblock %}


{% block card2%}
{% endblock %}

{% block jsbody%}
{% endblock %}

meenfee_dev/services/templates/add_subcategory.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type">Add Sub Category</h2>
{% endblock %}
{% block card%}

<form class="form-horizontal add_user" action="" method="post" enctype="multipart/form-data">
  <div class="panel panel-default">
    <div class="panel-heading user-form">
      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Category</label>
        <div class="col-md-3 offset-md-7">
          <select class="form-control" id="category" name="category" onchange="getval(this);">
            <option value="0">--Select--</option>
            {% for category in category %}
            <option value={{category.0}} Selected="Selected"> {{category.1}}</option>

            {% endfor %}
          </select>

        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Sub Category</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="subcategory" type="text" required name="subcategory"
            placeholder="Sub Category">
        </div>
      </div>


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Sub Category (Arabic)</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control"  dir="rtl" id="subcategory_arabic" type="text" required name="subcategory_arabic"
            placeholder="تصنيف فرعي">
        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="user_address">Description</label>
        <div class="col-md-4 offset-md-3">
          <textarea class="form-control" id="description" required name="description" rows="5"
            placeholder="Description..."></textarea>
        </div>
      </div>
      <div class="card-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="fa fa-dot-circle-o"></i> Submit</button>
        <button class="btn btn-sm btn-danger" type="reset">
          <i class="fa fa-ban"></i> Reset</button>
      </div>
    </div>
  </div>
  </div>
</form>
{% endblock %}
{% block card2%}
{% endblock %}
{% block jsbody%}
{%endblock%}

meenfee_dev/services/templates/detail_subcategory.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type" xmlns="http://www.w3.org/1999/html">Related Sub Category List</h2>
{% endblock %}
{% block card%}
<style>
</style>
<form role="form" method="post" name="detailform" id="detailform">{% csrf_token %}
<div class="panel panel-default">
<div class="panel-heading">  
</div>
 <!-- /.panel-heading -->
<div class="panel-body">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab" id="tab-main">Sub Category</a></li> 
         
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1">
            
             <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="subcDataList">
                    <thead>
                        <tr>
                            <th>#</th>  
                            <th>Sub Category Name</th>
                            <th>Description</th>                           
                           
                        </tr>
                    </thead>
                    <tbody id="tab1-tbody">{% csrf_token %}
             		  {% for subcatelist in object_list %}             		  			
									<tr>
                                     <td>{{ forloop.counter }}</td>                                    
                                    <td>{{ subcatelist.subcategory }}</td> 
                                    <td>{{ subcatelist.description }}</td> 
                                </tr>								
                             {% endfor %}  
                    </tbody>
                </table>
            <!-- /.table-responsive --> 
             </div>
        </div>
        </div>
    </div>
</div>
</div>
</form>
<!-- /.panel-body 1-->
{% endblock %}
{% block card2%}
{%endblock%}
{% block jsbody%}

{%endblock%}

meenfee_dev/services/templates/edit_service.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type">Edit Service</h2>
{% endblock %}
{% block card%}

<form class="form-horizontal add_user" action="" method="post" enctype="multipart/form-data">
  <div class="panel panel-default">
    <div class="panel-heading user-form">


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Category</label>
        <div class="col-md-3 offset-md-7">
          <select class="form-control" id="category" name="category" onchange="getval(this);">
            <option value="0" Selected="Selected">--Select--</option>
            {% for category in catData %}
            {% ifequal servicedata.cat_id category.id %}
            <option value={{category.id}} Selected="Selected"> {{category.category}}</option>
            {% else %}
            <option value={{category.id}}>{{category.category}}</option>
            {% endifequal %}
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Sub Category</label>
        <div class="col-md-3 offset-md-7">
          <select class="form-control" id="subcategory" name="subcategory">
            <option value="0">--Select--</option>
            {% for scategory in scatData %}
            {% ifequal servicedata.scat_id scategory.id %}
            <option value={{scategory.id}} Selected="Selected">{{scategory.subcategory}}</option>
            {% else %}
            <option value={{scategory.id}}>{{scategory.subcategory}}</option>
            {% endifequal %}
            {% endfor %}
          </select>

        </div>
      </div>



      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Service Name</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="service_name" type="text" value="{{servicedata.name}}" required
            name="service_name">

        </div>
      </div>




      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Project Type</label>
        <div class="col-md-3 offset-md-7">
          <select class="form-control" id="price_type" name="price_type">
            <option value="1">Hourly</option>
            <option value="2">Monthly</option>
          </select>

        </div>
      </div>




      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Service Price</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="service_pricing" type="number" min="1" step="0.01" max="1000000000" value="{{servicedata.price}}"
            required name="service_pricing" placeholder="Price">

        </div>
      </div>

      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Skill Level</label>
        <div class="col-md-4 offset-md-3">
          <input class="form-control" id="levelskill" type="text" pattern="\d*" value="{{servicedata.levelskill}}"
            required name="levelskill" placeholder="Skill">

        </div>
      </div>



      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="text-input">Experience</label>
        <div class="col-md-3 offset-md-7">
          <select class="form-control" id="experience" name="experience">
            <option value="beginner">Beginner</option>
            <option value="intermediate">Intermediate</option>
            <option value="professional">Professional</option>
            <option value="expert">Expert</option>

          </select>

        </div>
      </div>



      <!-- 
                      <div class="form-group row">
                        <label class="col-md-2 col-form-label" for="text-input">Service Image</label>
                        <div class="col-md-4 offset-md-3">
                          <input class="form-control"  id="id_image" type="file"  name="image" >
                         
                        </div>
                      </div>       -->


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="user_address">Quote at Request</label>
        <div class="col-md-4 offset-md-3">
          {% if servicedata.qar  %}
          <input type="checkbox" id="quote_at_request" name="quote_at_request" checked value="1">
          {% else %}
          <input type="checkbox" id="quote_at_request" name="quote_at_request" value="0">
          {% endif %}

        </div>
      </div>


      <div class="form-group row">
        <label class="col-md-2 col-form-label" for="user_address">Description </label>
        <div class="col-md-4 offset-md-3">
          <input type="hidden" id="data_id" name="data_id" value="{{servicedata.id}}" />
          <textarea class="form-control" id="description" required name="description"
            rows="5">{{servicedata.description}}</textarea>
        </div>
      </div>




      <div class="card-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="fa fa-dot-circle-o"></i> Submit</button>
        <button class="btn btn-sm btn-danger">
          <i class="fa fa-ban"></i> Back</button>
      </div>
    </div>
  </div>
  </div>
</form>
{% endblock %}
{% block card2%}
{% endblock %}

{% block jsbody%}

<script type="text/javascript">
  function getval(sel) {
    if (typeof sel == 'object') {
      selId = sel.value;
    }
    $.ajax({
      type: "GET",
      url: "{% url 'get_table_values' %}",
      data: {
        'id': selId,
      },
      success: function (result) {
        var ddHtml = '';
        //ddHtml+='<option >--Select--</option>';
        console.log(result);
        if (result.qs_len != '0') {
          $.each(result.qs, function (key, value) {
            var valCode = value.subcate;
            var valId = value.id;
            ddHtml += '<option value=' + valId + ' selected>' + valCode + '</option>';
            $("#subcategory").html(ddHtml);
          });
        } else {
          $("#subcategory").val('')
          //$("#subcategory").attr('disabled', 'disabled');
        }
      }
    });
  }
</script>
{%endblock%}

meenfee_dev/services/templates/mod_rating.html
{% extends 'base.html' %}
{% load static %}
{% block pageheadername %}
<h2 class="page-header user_type">Moderate Rating</h2>
{% endblock %}
{% block card%}
 
<form class="form-horizontal add_user" action="" method="post" enctype="multipart/form-data">
<div class="panel panel-default">
<div class="panel-heading user-form">         
  
  					                      
                       <div class="form-group row">
                        <label class="col-md-2 col-form-label" for="text-input">Category Name</label>
                        <div class="col-md-4 offset-md-3">
                          <input class="form-control" id="name" type="text" required name="name" placeholder="Category">
                         
                        </div>
                      </div>
                      
                      <div class="form-group row">
                        <label class="col-md-2 col-form-label" for="user_address">Description</label>
                        <div class="col-md-4 offset-md-3">
                          <textarea class="form-control" id="description" required name="description" rows="5" placeholder="Description..."></textarea>
                        </div>
                      </div>
                      
                                         
                    
                     <div class="card-footer">
                    <button class="btn btn-sm btn-primary" type="submit">
                      <i class="fa fa-dot-circle-o"></i> Submit</button>
                    <button class="btn btn-sm btn-danger" type="reset">
                      <i class="fa fa-ban"></i> Reset</button>
                  </div>
</div>
</div>
</div>
</form>
{% endblock %}
 {% block card2%}
 {% endblock %}

{% block jsbody%}
{%endblock%}